### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Alsan** [EXALAB/Busybox-Installer-No-Root#2]
I've follow all the instructions to install the busybox, not every command I use is command not found, so, what is the proper way to use it?

**Comment by jEstefani** [comment]
Para que sirve la aplicasion ?????

**Comment by sebma** [comment]
Here's what I type in the terminal : 

```
$ [ "$HOME" = "/" ] && export busyBoxPATH=/sdcard/Android/data/exa.free.bbin/files || export busyBoxPATH=$HOME/Android/data/exa.free.bbin/files
$ ls $busyBoxPATH/busybox
/sdcard/Android/data/exa.free.bbin/files/busybox
$ export PATH=$PATH:$busyBoxPATH
$ busybox
```

**Comment by sebma** [comment]
@rimsineman4 Why did you create issue #6 with my [comment](https://github.com/EXALAB/Busybox-Installer-No-Root/issues/2#issuecomment-564621027) ?

**Comment by Alsan** [comment]
> @Alsan Here's what I type in the terminal (please do not type the leading `$ `, it's my shell `PS1` prompt) :
> 
> ```shell
> $ [ "$HOME" = "/" ] && HOME=/sdcard
> $ [ "$HOME" = "/data" ] && export busyBoxPATH=/data/data/exa.free.bbin/files || export busyBoxPATH=$HOME/Android/data/exa.free.bbin/files
> $ ls $busyBoxPATH/busybox
> /sdcard/Android/data/exa.free.bbin/files/busybox
> $ export PATH=$PATH:$busyBoxPATH
> $ busybox --help
> ```

ok, after some investigation, i found that mine is installed at `/system/xbin/box`. Might be it's due to I'm using Android 10 and v1.80 release of this app.

```bash
# /system/xbin is already in my PATH env variable
box --help
```

**Comment by rmjspaz7284** [comment]
Jy
